### PR TITLE
Better unpenalized var handling

### LINKED ISSUE #22: cross_validate_path gen keyword arg does not work
https://github.com/JuliaStats/Lasso.jl/blob/55718966db53679e333d8a94749e8722b082796c/src/cross_validation.jl#L27-L36

For example,

```julia
using Lasso

X = rand(100, 5)
y = rand([0., 1.], 100)

path = fit(LassoPath, X, y)
cross_validate_path(path)
```

produces an error `UndefVarError: y not defined`. Should the default value for `gen` be changed to `gen=Kfold(length(path.m.rr.y), 10)` (or similar using a function to grab `y` from the `RegularizationPath`)?

### LINKED ISSUE #25: package could not be compiled on Julia 0.7
currently Lasso could not be compiled on Version 0.7.0 (2018-08-08 06:46 UTC).
```julia
julia> using Lasso
[ Info: Precompiling Lasso [b4fcebef-c861-5a0f-a7e2-ba9dc32b180a]
ERROR: LoadError: UndefVarError: df not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] top-level scope at none:2
 [7] eval at ./boot.jl:319 [inlined]
 [8] eval(::Expr) at ./client.jl:399
 [9] top-level scope at ./none:3
in expression starting at /Users/xua/.julia/packages/Lasso/GBbsl/src/Lasso.jl:360
ERROR: Failed to precompile Lasso [b4fcebef-c861-5a0f-a7e2-ba9dc32b180a] to /Users/xua/.julia/compiled/v0.7/Lasso/Djwuj.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1185
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
```

### PR DESCRIPTION
**Pull request by AsafManela**
- Greatly improved unpenalized var handling by conforming to approach taken in R's glmnet and gamlr, where an explanatory variable with a zero penalty factor is included in the base / null model that is used as a starting point for the regularization path.
The two following keyword arguments were added to allow us to compare in test/gammalasso.jl against gamlr:
  - `stopearly` allows the user to disable early stopping of regularization path
  - `standardizeω` allows the user to disable standardization of penalty factors
These behaviors both happen by default in glmnet but not gamlr

Note: a large number of csv test case files were changed slightly because we standardize X a bit differently than the approach in gamlr. The new test cases compare an unstandardized version.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It would be great if you could split these changes separate PRs such that they can be reviewed independently. In particular to have the bug fixes and performance enhancements separated.

**Comment by andreasnoack** [comment]
Thanks. Would be great if you could rebase this one.

**Comment by AsafManela** [comment]
Rebased. Thanks for being so responsive!

**Comment by andreasnoack** [comment]
@simonster Do you have time to review this?

**Comment by AsafManela** [comment]
bump

**Pull request merged**
